check for .env

diff --git a/update b/update
--- a/update
+++ b/update
@@ -1,2 +1,12 @@
 #! /bin/sh
+BASEDIR=$(dirname "$(readlink -f "$0")")
+
+die() {
+    echo
+    echo "$@"
+    exit 1
+}
+
+[ -f "$BASEDIR/.env" ] || die "Missing .env"
+
 docker compose pull && docker compose up -d
